FROM maven:3.6.3-jdk-8

ARG GIT_REPO_NAME
ARG GIT_BASE
ARG GIT_USER
ARG APPLICATION_NAME
ARG VERSION
ARG TYPE

RUN apt-get update && apt-get install -y git && apt-get install -y curl

RUN rm -rf /var/lib/apt/lists/*

RUN git clone ${GIT_BASE}/${GIT_USER}/${GIT_REPO_NAME}.git

RUN cd ${GIT_REPO_NAME}

WORKDIR ./${GIT_REPO_NAME}

RUN mvn clean install

RUN cp ./target/${APPLICATION_NAME}-${VERSION}.${TYPE} /${APPLICATION_NAME}-${VERSION}.${TYPE}

EXPOSE 8080

WORKDIR /perf-run

COPY pom.xml .

RUN mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline

COPY . .

RUN chmod 777 -R /perf-run /${APPLICATION_NAME}-${VERSION}.${TYPE}

RUN sed -i -e 's/\r$//' /perf-run/entrypoint.sh
